AWSTemplateFormatVersion: '2010-09-09'
Description: 'server

  Sample SAM Template for server

  '
Globals:
  Api:
    Cors:
      AllowHeaders: '''Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'''
      AllowMethods: '''DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'''
      AllowOrigin: '''*'''
  Function:
    Timeout: 5
Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: s3://vue-go-test/ead15ce2b0e9a1337783d7422a42fd16
      Events:
        CatchAll:
          Properties:
            Method: GET
            Path: /hello/{personName}
          Type: Api
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
  TaskFetcherFunction:
    Properties:
      CodeUri: s3://vue-go-test/ff5c2f5d95fd81a4e359a052b09a6efd
      Events:
        CatchAll:
          Properties:
            Method: GET
            Path: /users/{userID}/tasks
          Type: Api
      Handler: task-fetcher
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
  TaskRegisterFunction:
    Properties:
      CodeUri: s3://vue-go-test/f60653fcf1a255578eded76e6ed94695
      Events:
        CatchAll:
          Properties:
            Method: POST
            Path: /tasks
          Type: Api
      Handler: task-register
      Policies: AmazonDynamoDBFullAccess
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
